### ISSUE TITLE
ToDo list (TBC)

### ISSUE THREAD

**Issue by saraghsm** [JohnEnev/DSR-competition-team1#15]
Hi @JohnEnev ,

a few changes are needed in modules/feature_eng.py

Thanks,
Sara

**Bug fix:**

return df_train -> return df_new

https://github.com/JohnEnev/DSR-competition-team1/blob/d811ecb2314bafdc457fda3e4dcbbf4a557078f8/modules/feature_eng.py#L90

https://github.com/JohnEnev/DSR-competition-team1/blob/d811ecb2314bafdc457fda3e4dcbbf4a557078f8/modules/feature_eng.py#L104

**Minor editing:** 

train_df -> df

https://github.com/JohnEnev/DSR-competition-team1/blob/963d243abe3a474dc0323a8b111d1b5246e07f27/modules/feature_eng.py#L40

**Comment by JohnEnev** [comment]
Fixed - thanks
